/* ============================================================
   QuizMaster — questions.js
   180-question bank: 6 subjects × 3 levels × 10 questions
   Each question: { q, options[], answer, explanation }
   ============================================================ */

const QUESTION_BANK = {

  /* ==================== PYTHON ==================== */
  "Python": {
    "Easy": [
      { q: "What keyword is used to define a function in Python?", options: ["func", "def", "function", "define"], answer: "def", explanation: "'def' is the keyword used to define functions in Python, e.g. def my_func():." },
      { q: "Which symbol is used for single-line comments in Python?", options: ["//", "/* */", "#", "--"], answer: "#", explanation: "Python uses '#' for single-line comments. Multi-line strings (triple-quotes) are often used as block comments." },
      { q: "What does len([1, 2, 3]) return?", options: ["2", "3", "4", "None"], answer: "3", explanation: "len() returns the number of items in an object. The list [1,2,3] has 3 elements." },
      { q: "Which data type stores True or False values?", options: ["int", "str", "bool", "float"], answer: "bool", explanation: "The bool (Boolean) type stores True or False. Internally True=1, False=0." },
      { q: "How do you create an empty dictionary?", options: ["[]", "()", "{}", "dict[]"], answer: "{}", explanation: "An empty dict is created with {} (or dict()). Square brackets create a list." },
      { q: "What is the output of type([]) in Python?", options: ["<class 'list'>", "<class 'array'>", "<class 'tuple'>", "<class 'dict'>"], answer: "<class 'list'>", explanation: "[] creates an empty list, so type([]) returns <class 'list'>." },
      { q: "Which function reads user input in Python 3?", options: ["scanf()", "readline()", "input()", "read()"], answer: "input()", explanation: "input() is the built-in function that reads a line from standard input in Python 3." },
      { q: "What is the index of the first element in a Python list?", options: ["1", "0", "-1", "None"], answer: "0", explanation: "Python uses 0-based indexing. my_list[0] gives the first element." },
      { q: "Which operator is used for exponentiation in Python?", options: ["^", "**", "^^", "exp()"], answer: "**", explanation: "The ** operator raises a number to a power, e.g. 2 ** 3 = 8." },
      { q: "What keyword is used to import a module in Python?", options: ["include", "require", "import", "use"], answer: "import", explanation: "'import' loads a module, e.g. import math lets you use math.sqrt()." }
    ],
    "Medium": [
      { q: "What is a lambda function in Python?", options: ["A named function defined with def", "An anonymous single-expression function", "A class method", "A built-in function"], answer: "An anonymous single-expression function", explanation: "Lambda creates an anonymous function: lambda x: x*2 is equivalent to def f(x): return x*2." },
      { q: "Which data type is immutable?", options: ["List", "Dictionary", "Set", "Tuple"], answer: "Tuple", explanation: "Tuples are immutable — elements cannot be changed, added, or removed after creation." },
      { q: "What does *args do in a function definition?", options: ["Passes keyword arguments", "Allows any number of positional arguments", "Defines default arguments", "Creates global variables"], answer: "Allows any number of positional arguments", explanation: "*args collects extra positional arguments into a tuple, enabling flexible function signatures." },
      { q: "What does [x**2 for x in range(4)] evaluate to?", options: ["[1,4,9,16]", "[0,1,4,9]", "[0,1,2,3]", "[4,9,16,25]"], answer: "[0,1,4,9]", explanation: "range(4) yields 0,1,2,3. Squaring each: 0²=0, 1²=1, 2²=4, 3²=9 → [0,1,4,9]." },
      { q: "Which method removes and returns the last element of a list?", options: ["remove()", "delete()", "pop()", "discard()"], answer: "pop()", explanation: "list.pop() removes and returns the last element (or the element at a given index)." },
      { q: "What is the purpose of the 'pass' statement?", options: ["Exit a loop", "Return None", "Serve as a placeholder — does nothing", "Skip to the next iteration"], answer: "Serve as a placeholder — does nothing", explanation: "'pass' is a null operation. It's used where Python syntax requires a statement but no action is needed." },
      { q: "Which operator performs floor division?", options: ["/", "//", "%", "**"], answer: "//", explanation: "// performs integer (floor) division: 7 // 2 = 3. The / operator returns a float." },
      { q: "How is exception handling structured in Python?", options: ["try-catch", "try-except", "try-handle", "begin-rescue"], answer: "try-except", explanation: "Python uses try-except (optionally with else and finally) blocks to handle exceptions." },
      { q: "What does the 'self' keyword represent inside a class method?", options: ["The class itself", "The parent class", "The current instance of the class", "A static reference"], answer: "The current instance of the class", explanation: "'self' refers to the object on which the method is called and gives access to instance attributes." },
      { q: "What is the result of 'hello'[::-1]?", options: ["hello", "olleh", "ello", "helo"], answer: "olleh", explanation: "[::-1] is a slice with step -1, which reverses the string. 'hello' reversed is 'olleh'." }
    ],
    "Hard": [
      { q: "What is the Global Interpreter Lock (GIL) in CPython?", options: ["A memory allocator", "A mutex allowing only one thread to execute Python bytecode at a time", "A garbage collector", "A JIT compiler"], answer: "A mutex allowing only one thread to execute Python bytecode at a time", explanation: "The GIL prevents true multi-threading in CPython but doesn't affect multi-processing or I/O-bound threads." },
      { q: "What is the difference between __str__ and __repr__?", options: ["No difference", "__str__ is user-friendly; __repr__ is developer-friendly and unambiguous", "__repr__ is shown to users; __str__ to developers", "__str__ works only for numbers"], answer: "__str__ is user-friendly; __repr__ is developer-friendly and unambiguous", explanation: "__str__ formats objects for display; __repr__ gives a precise representation that ideally eval()s back to the object." },
      { q: "What is a generator in Python?", options: ["A function that returns a list", "A function using 'yield' to produce values lazily one at a time", "A class decorator", "A memory allocator"], answer: "A function using 'yield' to produce values lazily one at a time", explanation: "Generators use yield to suspend and resume execution, enabling memory-efficient iteration over large datasets." },
      { q: "What does @staticmethod do?", options: ["Makes a method instance-specific", "Defines a method that receives no implicit first argument (no self/cls)", "Binds a method to the class object", "Creates a class property"], answer: "Defines a method that receives no implicit first argument (no self/cls)", explanation: "@staticmethod defines a method that belongs to a class namespace but doesn't receive self or cls." },
      { q: "What is Method Resolution Order (MRO) in Python?", options: ["The order methods are defined in a class", "The order Python searches base classes when resolving method calls", "The execution order of methods", "The order of method deletion"], answer: "The order Python searches base classes when resolving method calls", explanation: "MRO (using C3 linearization) defines which superclass method is called in multiple inheritance scenarios." },
      { q: "What is the difference between copy.copy() and copy.deepcopy()?", options: ["Identical behavior", "copy() is shallow (nested objects are references); deepcopy() recursively copies all nested objects", "deepcopy() only copies numbers", "copy() creates independent nested copies"], answer: "copy() is shallow (nested objects are references); deepcopy() recursively copies all nested objects", explanation: "Shallow copy creates a new object but shares nested objects; deepcopy creates fully independent copies." },
      { q: "What does collections.defaultdict provide?", options: ["Sorts a dictionary by value", "A default value factory for missing keys", "Removes duplicates from a dict", "Creates an ordered dictionary"], answer: "A default value factory for missing keys", explanation: "defaultdict(list) automatically initializes missing keys to [] instead of raising KeyError." },
      { q: "What is the purpose of __slots__ in a Python class?", options: ["Defines allowed instance attributes, saving memory over __dict__", "Defines class methods", "Creates getter/setter properties", "Manages inheritance hierarchy"], answer: "Defines allowed instance attributes, saving memory over __dict__", explanation: "__slots__ replaces the per-instance __dict__ with a fixed-size array, reducing memory for large numbers of objects." },
      { q: "What do __enter__ and __exit__ implement?", options: ["Constructor/destructor pattern", "The context manager protocol used with 'with' statements", "Iterator protocol", "Exception chaining"], answer: "The context manager protocol used with 'with' statements", explanation: "__enter__ sets up the context; __exit__ cleans up, making 'with' safe for resource management." },
      { q: "What is a metaclass in Python?", options: ["A parent class", "A class whose instances are classes themselves", "An abstract base class", "A type annotation"], answer: "A class whose instances are classes themselves", explanation: "Metaclasses control class creation. 'type' is the default metaclass. Custom metaclasses allow you to modify class behavior at creation time." }
    ]
  },

  /* ==================== AI ==================== */
  "AI": {
    "Easy": [
      { q: "What does AI stand for?", options: ["Automated Integration", "Artificial Intelligence", "Advanced Interface", "Analog Input"], answer: "Artificial Intelligence", explanation: "AI (Artificial Intelligence) is the simulation of human-like intelligence processes by computer systems." },
      { q: "Which is a key subfield of Artificial Intelligence?", options: ["Machine Learning", "Network Security", "Database Design", "Web Development"], answer: "Machine Learning", explanation: "Machine Learning enables systems to learn from data without being explicitly programmed." },
      { q: "What is a neural network inspired by?", options: ["Computer circuits", "The human brain", "Mathematical equations only", "Statistical models"], answer: "The human brain", explanation: "Artificial neural networks loosely model how biological neurons in the brain process information." },
      { q: "What type of AI can perform only specific tasks?", options: ["General AI (AGI)", "Super AI", "Narrow AI", "Wide AI"], answer: "Narrow AI", explanation: "Narrow (Weak) AI is designed for one specific task, e.g., facial recognition or playing chess." },
      { q: "What does 'training data' mean in machine learning?", options: ["Data used to test a model", "Data used to teach/train a model", "Encrypted production data", "Data used in deployment"], answer: "Data used to teach/train a model", explanation: "Training data is the labeled or unlabeled dataset used to fit a machine learning model." },
      { q: "Which of the following is an example of supervised learning?", options: ["K-Means Clustering", "Email Spam Detection", "Principal Component Analysis", "Anomaly Detection"], answer: "Email Spam Detection", explanation: "Spam detection uses labeled examples (spam/not-spam), so it's supervised learning." },
      { q: "What does NLP stand for?", options: ["Natural Language Processing", "Neural Layer Protocol", "Network Learning Program", "None of the above"], answer: "Natural Language Processing", explanation: "NLP is a branch of AI that enables computers to understand, interpret, and generate human language." },
      { q: "Which programming language is most commonly used in AI/ML?", options: ["Java", "C++", "Python", "Ruby"], answer: "Python", explanation: "Python dominates AI/ML due to its simplicity, rich libraries (TensorFlow, PyTorch, scikit-learn), and community." },
      { q: "What is Computer Vision?", options: ["Improving monitor resolution", "Enabling computers to interpret and analyze visual data", "Designing camera hardware", "Programming graphics APIs"], answer: "Enabling computers to interpret and analyze visual data", explanation: "Computer Vision is an AI field that trains computers to derive meaningful information from images and videos." },
      { q: "What is Reinforcement Learning?", options: ["Learning from labeled data", "An agent learning by receiving rewards/penalties from its environment", "Unsupervised clustering", "A neural network type"], answer: "An agent learning by receiving rewards/penalties from its environment", explanation: "In RL, an agent interacts with an environment, taking actions to maximize cumulative reward." }
    ],
    "Medium": [
      { q: "What is overfitting in machine learning?", options: ["Model performs well on new data", "Model memorizes training data and fails to generalize to new data", "Model has too few parameters", "Model trains too slowly"], answer: "Model memorizes training data and fails to generalize to new data", explanation: "Overfitting happens when a model learns noise in training data, causing poor performance on unseen data." },
      { q: "What is the purpose of the activation function in neural networks?", options: ["To initialize weights", "To introduce non-linearity so the network can learn complex patterns", "To normalize inputs", "To reduce overfitting"], answer: "To introduce non-linearity so the network can learn complex patterns", explanation: "Without non-linear activations, stacked linear layers collapse to a single linear transformation." },
      { q: "What is backpropagation?", options: ["A type of neural network", "An algorithm that computes gradients and propagates them backward to update weights", "A data preprocessing technique", "A clustering algorithm"], answer: "An algorithm that computes gradients and propagates them backward to update weights", explanation: "Backpropagation applies the chain rule to compute gradients of the loss with respect to each weight." },
      { q: "What is K-Means clustering?", options: ["A supervised classification algorithm", "An unsupervised algorithm that groups data into K clusters by minimizing intra-cluster distance", "A dimensionality reduction technique", "A regression method"], answer: "An unsupervised algorithm that groups data into K clusters by minimizing intra-cluster distance", explanation: "K-Means iteratively assigns points to the nearest centroid and recomputes centroids until convergence." },
      { q: "What is the purpose of dropout in neural networks?", options: ["Speed up training", "Reduce overfitting by randomly disabling neurons during training", "Add more hidden layers", "Normalize activations"], answer: "Reduce overfitting by randomly disabling neurons during training", explanation: "Dropout randomly zeroes a fraction of activations each training step, acting as implicit ensemble regularization." },
      { q: "What is transfer learning?", options: ["Copying data between systems", "Reusing a pre-trained model and fine-tuning it on a new, related task", "Training multiple models simultaneously", "Sending model weights over a network"], answer: "Reusing a pre-trained model and fine-tuning it on a new, related task", explanation: "Transfer learning leverages features learned on large datasets (e.g., ImageNet) for smaller domain-specific tasks." },
      { q: "What metric evaluates classification model performance?", options: ["Mean Squared Error", "R-Squared", "Accuracy and F1-Score", "Silhouette Score"], answer: "Accuracy and F1-Score", explanation: "Accuracy measures overall correctness; F1-Score balances precision and recall, important for imbalanced datasets." },
      { q: "What is a hyperparameter?", options: ["A parameter learned from data", "A configuration value set before training that controls the learning process", "The model's output", "A feature in the dataset"], answer: "A configuration value set before training that controls the learning process", explanation: "Hyperparameters (learning rate, batch size, tree depth) are not learned — they are chosen by the practitioner." },
      { q: "What is the difference between supervised and unsupervised learning?", options: ["Speed of training", "Supervised uses labeled data; unsupervised finds patterns without labels", "Number of features", "Dataset size"], answer: "Supervised uses labeled data; unsupervised finds patterns without labels", explanation: "Supervised: predict labels (classification/regression). Unsupervised: discover structure (clustering/dimensionality reduction)." },
      { q: "What is a confusion matrix?", options: ["A matrix showing model errors only", "A table showing TP, FP, TN, FN for classification evaluation", "A weight initialization matrix", "A cost function representation"], answer: "A table showing TP, FP, TN, FN for classification evaluation", explanation: "The confusion matrix breaks down predictions into True/False Positives/Negatives, enabling precision, recall, and F1 calculation." }
    ],
    "Hard": [
      { q: "What is the Vanishing Gradient Problem?", options: ["Gradients become too large (explode)", "Gradients become extremely small during backprop, preventing early layers from learning", "Loss function doesn't converge", "Model runs out of memory"], answer: "Gradients become extremely small during backprop, preventing early layers from learning", explanation: "In deep sigmoid/tanh networks, gradients shrink exponentially through layers. Addressed by ReLU, batch norm, residual connections." },
      { q: "What is the Attention Mechanism in Transformers?", options: ["A memory management technique", "A mechanism that weighs the relevance of each input token when generating outputs", "An L2 regularization technique", "A type of activation function"], answer: "A mechanism that weighs the relevance of each input token when generating outputs", explanation: "Self-attention computes query-key-value scores to determine how much each position should influence other positions." },
      { q: "What are the Generator and Discriminator in a GAN?", options: ["Both generate data", "Generator creates fake data; Discriminator distinguishes real from fake — they compete adversarially", "Discriminator creates data; Generator classifies", "They serve identical purposes"], answer: "Generator creates fake data; Discriminator distinguishes real from fake — they compete adversarially", explanation: "The Generator improves to fool the Discriminator; the Discriminator improves to detect fakes — a minimax game." },
      { q: "What is Batch Normalization and why is it used?", options: ["Dividing data into mini-batches", "Normalizing layer inputs to stabilize and accelerate training", "Normalizing output predictions only", "A data augmentation method"], answer: "Normalizing layer inputs to stabilize and accelerate training", explanation: "BatchNorm normalizes activations across a mini-batch, reducing internal covariate shift and allowing higher learning rates." },
      { q: "What does BERT stand for and what makes it unique?", options: ["Basic Embedding Retrieval Transformer", "Bidirectional Encoder Representations from Transformers — reads text bidirectionally", "Base Evaluation and Reasoning Toolkit", "Batch Embedding Representation Tool"], answer: "Bidirectional Encoder Representations from Transformers — reads text bidirectionally", explanation: "BERT is pre-trained with masked language modeling on both left and right context simultaneously, unlike earlier unidirectional models." },
      { q: "What is the Bellman Equation in Reinforcement Learning?", options: ["A loss function for classification", "An equation expressing state value as immediate reward plus discounted future value", "A network weight update rule", "A policy gradient formula"], answer: "An equation expressing state value as immediate reward plus discounted future value", explanation: "V(s) = R + γ·max V(s'). It is the foundation of Q-learning and dynamic programming in RL." },
      { q: "What is the difference between L1 and L2 regularization?", options: ["L1 = squared weights penalty; L2 = absolute weights penalty", "L1 adds |w| to loss (promotes sparsity); L2 adds w² to loss (promotes small weights)", "They are identical in effect", "L2 is only used in neural networks"], answer: "L1 adds |w| to loss (promotes sparsity); L2 adds w² to loss (promotes small weights)", explanation: "L1 (Lasso) can zero out irrelevant features; L2 (Ridge) keeps all features small. Often combined as ElasticNet." },
      { q: "What is an Autoencoder used for?", options: ["A supervised image classifier", "An encoder-decoder that learns compressed latent representations and reconstructs inputs", "A type of decision tree", "A data normalization technique"], answer: "An encoder-decoder that learns compressed latent representations and reconstructs inputs", explanation: "Autoencoders are used for dimensionality reduction, denoising, anomaly detection, and generative modeling." },
      { q: "What is the role of the Softmax function in the output layer?", options: ["Introduce non-linearity in hidden layers", "Convert raw logit scores into a probability distribution that sums to 1", "Initialize model weights", "Normalize batch statistics"], answer: "Convert raw logit scores into a probability distribution that sums to 1", explanation: "Softmax(z_i) = exp(z_i) / Σexp(z_j). It enables multi-class classification with probabilistic output." },
      { q: "What is Q-Learning?", options: ["A supervised classification method", "A model-free RL algorithm that learns Q-values (action-state values) to derive an optimal policy", "A clustering technique", "A generative model"], answer: "A model-free RL algorithm that learns Q-values (action-state values) to derive an optimal policy", explanation: "Q-Learning updates Q(s,a) = Q(s,a) + α(R + γ max Q(s',a') - Q(s,a)). Deep Q-Networks (DQN) extend it with neural nets." }
    ]
  },

  /* ==================== WEB DEV ==================== */
  "Web Dev": {
    "Easy": [
      { q: "What does HTML stand for?", options: ["Hyper Text Markup Language", "Hyper Transfer Markup Language", "High Tech Markup Language", "Hyper Text Making Language"], answer: "Hyper Text Markup Language", explanation: "HTML is the standard markup language for creating the structure of web pages." },
      { q: "Which HTML tag creates the largest heading?", options: ["<h6>", "<heading>", "<h1>", "<head>"], answer: "<h1>", explanation: "<h1> is the most important heading tag. Headings go from <h1> (largest) to <h6> (smallest)." },
      { q: "What does CSS stand for?", options: ["Cascading Style Sheets", "Creative Style Syntax", "Computer Style Sheets", "Colorful Style Sheets"], answer: "Cascading Style Sheets", explanation: "CSS controls the visual presentation — layout, colors, fonts — of HTML documents." },
      { q: "Which CSS property changes text color?", options: ["text-color", "font-color", "color", "foreground-color"], answer: "color", explanation: "The 'color' property sets the foreground (text) color. Background color uses 'background-color'." },
      { q: "What is JavaScript primarily used for in web development?", options: ["Styling pages", "Database management", "Adding interactivity and dynamic behavior", "Server configuration"], answer: "Adding interactivity and dynamic behavior", explanation: "JavaScript enables event handling, DOM manipulation, animations, and communication with APIs." },
      { q: "Which HTML tag creates a hyperlink?", options: ["<link>", "<a>", "<href>", "<url>"], answer: "<a>", explanation: "The anchor (<a>) tag with an href attribute creates clickable hyperlinks." },
      { q: "What does DOM stand for?", options: ["Document Object Model", "Data Object Management", "Document Oriented Module", "Dynamic Object Markup"], answer: "Document Object Model", explanation: "The DOM is the browser's in-memory tree representation of an HTML document, manipulated via JavaScript." },
      { q: "Which HTML attribute specifies the image source?", options: ["href", "link", "src", "url"], answer: "src", explanation: "The 'src' attribute on <img> specifies the path or URL of the image to display." },
      { q: "What does the <div> element do?", options: ["Defines a hyperlink", "Groups block-level content for styling/layout", "Creates a dropdown", "Inserts a table"], answer: "Groups block-level content for styling/layout", explanation: "<div> is a generic block container used to group elements for CSS or JavaScript purposes." },
      { q: "Which HTML tag creates an unordered list?", options: ["<ol>", "<li>", "<list>", "<ul>"], answer: "<ul>", explanation: "<ul> creates a bulleted list; <ol> creates a numbered list. <li> is used for list items inside both." }
    ],
    "Medium": [
      { q: "What is the difference between == and === in JavaScript?", options: ["No difference", "=== checks value AND type (strict); == coerces types before comparing", "== checks type; === checks value only", "=== is only for object comparison"], answer: "=== checks value AND type (strict); == coerces types before comparing", explanation: "'1' == 1 is true (type coercion); '1' === 1 is false (different types). Always prefer ===." },
      { q: "What is the CSS box model?", options: ["A 3D layout technique", "The layers surrounding an element: content + padding + border + margin", "A flexbox utility", "A CSS grid system"], answer: "The layers surrounding an element: content + padding + border + margin", explanation: "Every element is a box. Understanding the box model is essential for accurate sizing and spacing." },
      { q: "What does localStorage.setItem() do?", options: ["Stores data on a server", "Persists a key-value pair in the browser across sessions", "Creates a temporary session cookie", "Caches an HTTP response"], answer: "Persists a key-value pair in the browser across sessions", explanation: "localStorage stores string key-value pairs that persist even after the browser is closed, unlike sessionStorage." },
      { q: "What does async/await do in JavaScript?", options: ["Makes code run faster", "Provides syntactic sugar for working with Promises in a synchronous style", "Creates parallel worker threads", "Defines class methods"], answer: "Provides syntactic sugar for working with Promises in a synchronous style", explanation: "async functions return Promises; await pauses execution until the Promise resolves, avoiding .then() chains." },
      { q: "What is Flexbox used for in CSS?", options: ["3D transformations", "Laying out elements along one axis (row or column) with flexible sizing", "Integrating databases", "Controlling animations"], answer: "Laying out elements along one axis (row or column) with flexible sizing", explanation: "Flexbox makes it easy to align, distribute, and order elements along a single axis responsively." },
      { q: "What is event bubbling in JavaScript?", options: ["Creating particle animations", "When an event fires on a child element, it propagates upward through ancestor elements", "Events propagating from parent to child", "A memory leak pattern"], answer: "When an event fires on a child element, it propagates upward through ancestor elements", explanation: "Click on a button inside a div — both the button and div receive the click event (unless stopPropagation() is called)." },
      { q: "What is a REST API?", options: ["Random Entry System Technology", "An API following Representational State Transfer principles using HTTP methods", "Real-time Event Streaming Technology", "Remote Execution Service Template"], answer: "An API following Representational State Transfer principles using HTTP methods", explanation: "REST APIs use GET/POST/PUT/DELETE over HTTP, are stateless, and return JSON or XML." },
      { q: "What is the difference between null and undefined in JavaScript?", options: ["They are identical", "null = explicitly set to 'no value'; undefined = declared but not yet assigned", "undefined is set explicitly; null is automatic", "Only null can be assigned to variables"], answer: "null = explicitly set to 'no value'; undefined = declared but not yet assigned", explanation: "typeof null === 'object' (historical bug); typeof undefined === 'undefined'." },
      { q: "What does CSS specificity determine?", options: ["How quickly CSS loads", "Which CSS rule wins when multiple rules target the same element", "The order rules are written in a file", "The total number of selectors"], answer: "Which CSS rule wins when multiple rules target the same element", explanation: "Specificity is calculated as (inline, ID, class, element). Higher specificity wins; equal specificity defers to source order." },
      { q: "What is a CSS media query used for?", options: ["Querying a database from CSS", "Applying styles conditionally based on device characteristics like screen width", "Importing external stylesheets", "Defining CSS animations"], answer: "Applying styles conditionally based on device characteristics like screen width", explanation: "@media (max-width: 768px) { } applies styles only on screens narrower than 768px, enabling responsive design." }
    ],
    "Hard": [
      { q: "What is the Virtual DOM and why does React use it?", options: ["A server-side copy of the DOM", "An in-memory representation of the DOM used to compute minimal updates efficiently", "A CSS variable system", "A database abstraction layer"], answer: "An in-memory representation of the DOM used to compute minimal updates efficiently", explanation: "React diffs the Virtual DOM to find the minimum set of real DOM mutations needed, greatly improving performance." },
      { q: "What is CORS and why does it exist?", options: ["A caching mechanism", "A browser security feature controlling cross-origin HTTP requests to prevent CSRF", "A CSS preprocessor", "A JavaScript runtime optimization"], answer: "A browser security feature controlling cross-origin HTTP requests to prevent CSRF", explanation: "Same-origin policy blocks cross-origin requests by default. CORS headers (Access-Control-Allow-Origin) opt-in to allow them." },
      { q: "What is a closure in JavaScript?", options: ["A function with no return value", "A function that retains access to its lexical scope even after the outer function has returned", "An arrow function definition", "A function that closes the browser tab"], answer: "A function that retains access to its lexical scope even after the outer function has returned", explanation: "Closures are fundamental to JS — they enable data privacy, currying, and callbacks that remember state." },
      { q: "What is Server-Side Rendering (SSR)?", options: ["HTML generated on the client by JavaScript", "HTML generated on the server and sent complete to the client", "Static HTML files served from CDN", "WebSocket-based rendering"], answer: "HTML generated on the server and sent complete to the client", explanation: "SSR improves initial page load time and SEO since the HTML is fully formed before JavaScript runs." },
      { q: "What are Service Workers?", options: ["Server-side request processors", "Background scripts that enable offline caching, push notifications, and background sync", "DOM manipulation helpers", "HTTP request interceptors running in Node.js"], answer: "Background scripts that enable offline caching, push notifications, and background sync", explanation: "Service Workers run in a separate thread, intercept network requests, and power Progressive Web Apps (PWAs)." },
      { q: "What is the difference between HTTP/1.1 and HTTP/2?", options: ["HTTP/2 adds encryption only", "HTTP/2 adds multiplexing, header compression, and server push over one TCP connection", "HTTP/1.1 is newer and faster", "No practical difference"], answer: "HTTP/2 adds multiplexing, header compression, and server push over one TCP connection", explanation: "HTTP/2 eliminates head-of-line blocking by multiplexing multiple streams over one connection." },
      { q: "What is Tree Shaking in JavaScript bundlers?", options: ["A CSS animation technique", "Eliminating unused (dead) code from the final bundle at build time", "A DOM traversal optimization", "A performance testing method"], answer: "Eliminating unused (dead) code from the final bundle at build time", explanation: "Bundlers like Webpack/Rollup analyze ES module import/export graphs and remove code never referenced." },
      { q: "What is a JavaScript Promise?", options: ["A callback function", "An object representing the eventual completion or failure of an asynchronous operation", "A synchronous function wrapper", "A type of Web Worker"], answer: "An object representing the eventual completion or failure of an asynchronous operation", explanation: "Promises have three states: pending, fulfilled, rejected. They support .then(), .catch(), .finally() chaining." },
      { q: "What is Content Security Policy (CSP)?", options: ["A data compression algorithm", "An HTTP header that specifies trusted content sources to prevent XSS attacks", "A CDN configuration standard", "A JavaScript sandboxing API"], answer: "An HTTP header that specifies trusted content sources to prevent XSS attacks", explanation: "CSP tells the browser which scripts, styles, images etc. are allowed, blocking injected malicious content." },
      { q: "What is the Intersection Observer API?", options: ["Detecting element size changes", "Asynchronously observing when elements enter or exit the viewport", "Measuring performance metrics", "Tracking mouse position over elements"], answer: "Asynchronously observing when elements enter or exit the viewport", explanation: "Intersection Observer is used for lazy loading images, infinite scroll, and triggering animations on scroll." }
    ]
  },

  /* ==================== DSA ==================== */
  "DSA": {
    "Easy": [
      { q: "What is the time complexity of accessing an element in an array by index?", options: ["O(n)", "O(log n)", "O(1)", "O(n²)"], answer: "O(1)", explanation: "Array elements are stored contiguously. Index access requires only one memory lookup — constant time O(1)." },
      { q: "Which data structure follows LIFO (Last In, First Out)?", options: ["Queue", "Stack", "Linked List", "Tree"], answer: "Stack", explanation: "A Stack follows LIFO — push adds to the top, pop removes from the top. Like a stack of plates." },
      { q: "Which data structure follows FIFO (First In, First Out)?", options: ["Stack", "Tree", "Queue", "Graph"], answer: "Queue", explanation: "A Queue follows FIFO — enqueue adds to the back, dequeue removes from the front. Like a ticket line." },
      { q: "What is the worst-case time complexity of Bubble Sort?", options: ["O(n)", "O(n log n)", "O(n²)", "O(1)"], answer: "O(n²)", explanation: "Bubble Sort compares all pairs in the worst case (reverse-sorted input), requiring n*(n-1)/2 comparisons." },
      { q: "What is a linked list?", options: ["An array with a fixed size", "A sequence of nodes where each node stores data and a pointer to the next node", "A sorted array", "A type of tree"], answer: "A sequence of nodes where each node stores data and a pointer to the next node", explanation: "Linked lists allow O(1) insertion/deletion at known positions but O(n) random access." },
      { q: "What is Binary Search?", options: ["Searching all elements sequentially", "Searching by halving the search space in a sorted array", "Searching with a hash function", "Searching through a tree"], answer: "Searching by halving the search space in a sorted array", explanation: "Binary search requires a sorted array. Each step eliminates half the remaining elements, achieving O(log n)." },
      { q: "What does DFS stand for?", options: ["Data First Search", "Depth First Search", "Direct Flow Search", "Distributed First Scan"], answer: "Depth First Search", explanation: "DFS explores as deep as possible along each branch before backtracking, using a stack (explicit or call stack)." },
      { q: "What does BFS stand for?", options: ["Backward First Search", "Breadth First Search", "Binary Fixed Search", "Base-level First Scan"], answer: "Breadth First Search", explanation: "BFS explores all nodes at the current depth level before moving to the next, using a queue." },
      { q: "What is a tree in data structures?", options: ["A linear data structure", "A hierarchical structure with a root node and child subtrees, with no cycles", "A graph with cycles", "A hash-based structure"], answer: "A hierarchical structure with a root node and child subtrees, with no cycles", explanation: "A tree with N nodes has exactly N-1 edges. Binary Search Trees, Heaps, and Tries are specialized trees." },
      { q: "What is a hash function used for?", options: ["Sorting data", "Mapping a key to a fixed-size index in a hash table", "Encrypting passwords only", "Comparing two arrays"], answer: "Mapping a key to a fixed-size index in a hash table", explanation: "Hash functions compute array indices from keys, enabling average O(1) lookup/insertion in hash tables." }
    ],
    "Medium": [
      { q: "What is the average-case time complexity of Quick Sort?", options: ["O(n)", "O(n²)", "O(n log n)", "O(log n)"], answer: "O(n log n)", explanation: "Quick Sort partitions around a pivot, averaging O(n log n). Worst case is O(n²) with a bad pivot choice." },
      { q: "What is dynamic programming?", options: ["Programming in dynamic languages", "Solving problems by breaking them into overlapping subproblems and caching results", "Real-time event-driven programming", "Object-oriented design patterns"], answer: "Solving problems by breaking them into overlapping subproblems and caching results", explanation: "DP avoids recomputation by storing solutions (memoization=top-down; tabulation=bottom-up). Key: optimal substructure + overlapping subproblems." },
      { q: "What is a Min-Heap?", options: ["A tree where parent > children", "A complete binary tree where parent ≤ children at all levels", "A sorted binary tree", "A balanced BST"], answer: "A complete binary tree where parent ≤ children at all levels", explanation: "The minimum element is always at the root. Used in priority queues and Dijkstra's algorithm." },
      { q: "What is the time complexity of inserting into a Heap?", options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"], answer: "O(log n)", explanation: "Heap insert adds at the end and sifts up — at most log n swaps for a heap of n elements." },
      { q: "What is Dijkstra's algorithm used for?", options: ["Sorting arrays", "Finding shortest paths from a source in a weighted graph with non-negative edges", "Detecting cycles in a graph", "Topological ordering"], answer: "Finding shortest paths from a source in a weighted graph with non-negative edges", explanation: "Dijkstra's uses a min-heap to greedily extract the nearest unvisited node, running in O((V+E) log V)." },
      { q: "What is memoization?", options: ["A hardware memory type", "Caching function call results to avoid redundant recomputation", "An in-place sorting optimization", "A recursion elimination technique"], answer: "Caching function call results to avoid redundant recomputation", explanation: "If fib(10) was computed before, return the cached result instead of recomputing the entire subtree." },
      { q: "What is the difference between BFS and DFS?", options: ["BFS uses a stack; DFS uses a queue", "BFS uses a queue and explores level by level; DFS uses a stack and explores deep first", "No algorithmic difference", "BFS works only on trees; DFS only on graphs"], answer: "BFS uses a queue and explores level by level; DFS uses a stack and explores deep first", explanation: "BFS finds shortest paths in unweighted graphs. DFS is better for cycle detection, topological sort, and path finding." },
      { q: "What is a Binary Search Tree (BST) property?", options: ["All nodes have 2 children", "Left child < parent < right child for every node", "Nodes are stored in sorted order in an array", "The tree is always balanced"], answer: "Left child < parent < right child for every node", explanation: "BST enables O(log n) search/insert/delete on average. Worst case O(n) for degenerate (sorted input) trees." },
      { q: "What is a graph in data structures?", options: ["A plotted chart", "A set of vertices (nodes) connected by edges, representing relationships", "A sorted hierarchical tree", "A 2D array"], answer: "A set of vertices (nodes) connected by edges, representing relationships", explanation: "Graphs model networks — social connections, roads, dependencies. Can be directed/undirected, weighted/unweighted." },
      { q: "What is the purpose of a Stack in function call management?", options: ["Sorting function calls", "The call stack tracks active function frames, enabling recursion and returning to callers", "Caching function results", "Managing heap memory allocation"], answer: "The call stack tracks active function frames, enabling recursion and returning to callers", explanation: "Each function call pushes a frame (local variables, return address) onto the call stack; return pops it." }
    ],
    "Hard": [
      { q: "What is the time complexity of Merge Sort?", options: ["O(n)", "O(n²)", "O(n log n)", "O(log n)"], answer: "O(n log n)", explanation: "Merge Sort divides the array (log n levels), merging takes O(n) per level → O(n log n) guaranteed." },
      { q: "What is a Red-Black Tree?", options: ["A colored binary tree balanced using 5 coloring invariants", "A tree that only stores red and black elements", "A BST sorted by element color", "A multi-way tree variant"], answer: "A colored binary tree balanced using 5 coloring invariants", explanation: "Red-Black Trees guarantee O(log n) operations. Rules: root is black, no two red nodes adjacent, equal black-height on all paths." },
      { q: "What is Topological Sorting used for?", options: ["Sorting numbers in ascending order", "Ordering vertices of a DAG respecting directed dependency edges", "Finding the shortest path", "Detecting connected components"], answer: "Ordering vertices of a DAG respecting directed dependency edges", explanation: "Used for task scheduling, build systems, course prerequisites. Only valid on DAGs — fails if a cycle exists." },
      { q: "What is Kruskal's algorithm?", options: ["Single-source shortest path", "Builds Minimum Spanning Tree by sorting edges by weight and adding non-cycle edges", "Maximum flow in a network", "Topological sort on DAG"], answer: "Builds Minimum Spanning Tree by sorting edges by weight and adding non-cycle edges", explanation: "Kruskal's sorts edges, then greedily adds the cheapest edge that doesn't create a cycle (uses Union-Find)." },
      { q: "What is amortized time complexity?", options: ["The worst-case time per single operation", "The average cost per operation over a sequence of operations", "The best-case time per operation", "The space-time trade-off"], answer: "The average cost per operation over a sequence of operations", explanation: "Dynamic array doubling is O(n) occasionally but O(1) amortized because most operations are O(1)." },
      { q: "What is a Trie (prefix tree) used for?", options: ["Sorting numbers efficiently", "Efficient string storage and prefix/autocomplete search in O(m) per query", "Graph traversal", "Priority queue operations"], answer: "Efficient string storage and prefix/autocomplete search in O(m) per query", explanation: "Tries store strings character by character. Each root-to-node path represents a prefix. O(m) search regardless of dictionary size." },
      { q: "When is Bellman-Ford preferred over Dijkstra's algorithm?", options: ["They are identical in applicability", "Bellman-Ford handles negative edge weights and detects negative cycles; Dijkstra doesn't", "Dijkstra handles negative weights; Bellman-Ford doesn't", "Bellman-Ford is always faster"], answer: "Bellman-Ford handles negative edge weights and detects negative cycles; Dijkstra doesn't", explanation: "Bellman-Ford relaxes all edges V-1 times → O(VE). It can detect negative cycles via a Vth relaxation pass." },
      { q: "What is the Floyd-Warshall algorithm?", options: ["Single-source shortest path using DP", "All-pairs shortest path using DP in O(V³) time", "Minimum spanning tree", "Maximum bipartite matching"], answer: "All-pairs shortest path using DP in O(V³) time", explanation: "Floyd-Warshall computes dist[i][j] for all pairs by considering each vertex k as an intermediate node." },
      { q: "What is a Segment Tree used for?", options: ["String matching algorithms", "Answering range queries (sum/min/max) and point updates in O(log n)", "Graph coloring problems", "Cycle detection in directed graphs"], answer: "Answering range queries (sum/min/max) and point updates in O(log n)", explanation: "Segment trees store aggregate information for array ranges. Range query O(log n), point update O(log n)." },
      { q: "What is the space complexity of recursive DFS on a graph with V vertices and E edges?", options: ["O(1)", "O(V)", "O(V+E)", "O(V²)"], answer: "O(V)", explanation: "The call stack depth is at most V (linear chain worst case). The visited array also takes O(V). Adjacency list representation is O(V+E) space overall." }
    ]
  },

  /* ==================== DBMS ==================== */
  "DBMS": {
    "Easy": [
      { q: "What does DBMS stand for?", options: ["Data Base Management System", "Digital Binary Management System", "Database Making Software", "Data Binding Module System"], answer: "Data Base Management System", explanation: "A DBMS is software that stores, retrieves, and manages data in a database (e.g., MySQL, PostgreSQL, Oracle)." },
      { q: "What is SQL?", options: ["Simple Query Language", "Structured Query Language", "System Query Logic", "Sequential Query Layout"], answer: "Structured Query Language", explanation: "SQL is the standard language for querying and managing relational databases." },
      { q: "Which SQL command retrieves data from a table?", options: ["INSERT", "UPDATE", "SELECT", "DELETE"], answer: "SELECT", explanation: "SELECT fetches rows from tables. e.g., SELECT * FROM students WHERE grade = 'A'." },
      { q: "What is a Primary Key?", options: ["A foreign key imported from another table", "A column (or set of columns) uniquely identifying each row — cannot be NULL or duplicate", "The first column of any table", "A key used only for searching"], answer: "A column (or set of columns) uniquely identifying each row — cannot be NULL or duplicate", explanation: "Primary keys enforce entity integrity. Every table should have a primary key." },
      { q: "What is a Foreign Key?", options: ["A key used internationally", "A column that references the Primary Key of another table, enforcing referential integrity", "A duplicate of the primary key", "A key for external user access"], answer: "A column that references the Primary Key of another table, enforcing referential integrity", explanation: "Foreign keys create relationships between tables and prevent orphan records (referential integrity)." },
      { q: "Which SQL command adds new records?", options: ["ADD", "UPDATE", "INSERT INTO", "CREATE"], answer: "INSERT INTO", explanation: "INSERT INTO table (col1, col2) VALUES (val1, val2) adds a new row to a table." },
      { q: "What does DDL stand for in SQL?", options: ["Data Definition Language", "Dynamic Data Logic", "Data Distribution Layer", "Document Definition Language"], answer: "Data Definition Language", explanation: "DDL commands (CREATE, ALTER, DROP, TRUNCATE) define and modify database schema/structure." },
      { q: "What is the purpose of the WHERE clause?", options: ["Groups rows", "Sorts results", "Filters rows based on a condition", "Joins two tables"], answer: "Filters rows based on a condition", explanation: "WHERE filters which rows are returned: SELECT * FROM orders WHERE amount > 1000." },
      { q: "Which SQL command updates existing records?", options: ["MODIFY", "CHANGE", "UPDATE", "ALTER"], answer: "UPDATE", explanation: "UPDATE table SET col = value WHERE condition modifies existing rows. Without WHERE it updates all rows!" },
      { q: "What does the ORDER BY clause do?", options: ["Filters rows", "Groups rows", "Sorts query results ascending or descending", "Joins tables"], answer: "Sorts query results ascending or descending", explanation: "ORDER BY col ASC/DESC sorts the result set. Default is ASC (ascending)." }
    ],
    "Medium": [
      { q: "What is normalization in DBMS?", options: ["Sorting data alphabetically", "Organizing tables to eliminate data redundancy and improve integrity", "Encrypting sensitive data", "Compressing the database"], answer: "Organizing tables to eliminate data redundancy and improve integrity", explanation: "Normalization (1NF→2NF→3NF→BCNF) removes update/delete/insert anomalies caused by redundant data." },
      { q: "What is 1NF (First Normal Form)?", options: ["Table has no columns", "Each column contains atomic (indivisible) values; no repeating groups", "Table has a primary key only", "Table has no foreign keys"], answer: "Each column contains atomic (indivisible) values; no repeating groups", explanation: "1NF requires atomic values. Example violation: storing multiple phone numbers in one column." },
      { q: "What is an INNER JOIN?", options: ["Returns all rows from both tables", "Returns only rows that have matching values in both joined tables", "Returns all rows from the left table", "Joins a table to itself"], answer: "Returns only rows that have matching values in both joined tables", explanation: "INNER JOIN is the most common join type. Rows without a match in either table are excluded." },
      { q: "What is the difference between INNER JOIN and LEFT JOIN?", options: ["No difference", "INNER JOIN returns only matches; LEFT JOIN returns all left rows plus matched right rows (NULLs for unmatched)", "LEFT JOIN returns only left table rows without matches", "INNER JOIN returns all rows from both tables"], answer: "INNER JOIN returns only matches; LEFT JOIN returns all left rows plus matched right rows (NULLs for unmatched)", explanation: "LEFT JOIN preserves all records from the left table even if no match exists in the right table." },
      { q: "What is an Index in a database?", options: ["The row number of a record", "A data structure (typically B-tree) that speeds up data retrieval at the cost of extra storage", "A foreign key reference", "A database backup copy"], answer: "A data structure (typically B-tree) that speeds up data retrieval at the cost of extra storage", explanation: "Indexes speed up SELECT queries but slow down INSERT/UPDATE/DELETE. Create indexes on frequently queried columns." },
      { q: "What does ACID stand for in database transactions?", options: ["Atomicity, Consistency, Isolation, Durability", "Automated Control In Database", "Accuracy, Completeness, Integrity, Dependability", "Authentication, Coding, Implementation, Deployment"], answer: "Atomicity, Consistency, Isolation, Durability", explanation: "ACID properties guarantee that database transactions are processed reliably even in the event of errors or failures." },
      { q: "What is a transaction in DBMS?", options: ["A financial record stored in a DB", "A unit of work that is Atomic, Consistent, Isolated, and Durable", "A stored procedure call", "A type of JOIN operation"], answer: "A unit of work that is Atomic, Consistent, Isolated, and Durable", explanation: "Either all operations in a transaction succeed (commit) or all are rolled back — partial success is impossible." },
      { q: "What is the purpose of GROUP BY in SQL?", options: ["Sorts result rows", "Groups rows with the same values into summary rows for use with aggregate functions", "Filters individual rows", "Merges two tables together"], answer: "Groups rows with the same values into summary rows for use with aggregate functions", explanation: "SELECT dept, AVG(salary) FROM employees GROUP BY dept — computes average salary per department." },
      { q: "What is a VIEW in SQL?", options: ["A physical copy of a table saved on disk", "A virtual table defined by a stored SELECT query", "A type of stored procedure", "An index on multiple columns"], answer: "A virtual table defined by a stored SELECT query", explanation: "Views simplify complex queries, provide security by restricting column access, and don't store data themselves." },
      { q: "What is the difference between DELETE and TRUNCATE?", options: ["No difference", "DELETE removes rows one-by-one with logging and can be rolled back; TRUNCATE removes all rows faster with minimal logging", "TRUNCATE logs each row deletion", "DELETE removes the table structure too"], answer: "DELETE removes rows one-by-one with logging and can be rolled back; TRUNCATE removes all rows faster with minimal logging", explanation: "DELETE is DML (can use WHERE, triggers fire, rollback possible); TRUNCATE is DDL (no WHERE, resets auto-increment, faster)." }
    ],
    "Hard": [
      { q: "What is a B+ Tree and why do databases use it for indexing?", options: ["A colored balanced BST for in-memory use", "A tree where all data lives in leaf nodes (linked list), optimizing range queries and disk reads", "A hash-based index structure", "A multi-level hash table"], answer: "A tree where all data lives in leaf nodes (linked list), optimizing range queries and disk reads", explanation: "B+ Trees match disk page sizes, minimize I/O, and enable range queries via the sorted linked leaf list." },
      { q: "What is a deadlock in DBMS and how is it prevented?", options: ["A database crash", "Two transactions each hold locks the other needs — causing infinite waiting. Prevented by ordering locks or timeouts", "An invalid query error", "A network timeout"], answer: "Two transactions each hold locks the other needs — causing infinite waiting. Prevented by ordering locks or timeouts", explanation: "Deadlock prevention: order resources, use timeouts, wait-die/wound-wait schemes, or deadlock detection + rollback." },
      { q: "What is query optimization?", options: ["Writing shorter SQL", "The DBMS finding the most efficient execution plan for a SQL query using statistics and cost models", "Caching all query results", "Removing redundant columns"], answer: "The DBMS finding the most efficient execution plan for a SQL query using statistics and cost models", explanation: "The query optimizer generates alternative plans, estimates costs using column statistics and histograms, and picks the cheapest." },
      { q: "What is denormalization and when is it used?", options: ["Removing all indexes from a table", "Intentionally adding redundancy to improve read performance in read-heavy workloads", "Converting RDBMS to NoSQL", "Removing all foreign key constraints"], answer: "Intentionally adding redundancy to improve read performance in read-heavy workloads", explanation: "Denormalization pre-joins data, reducing expensive runtime JOINs. Common in data warehouses and OLAP systems." },
      { q: "What is the difference between optimistic and pessimistic concurrency control?", options: ["They are identical mechanisms", "Optimistic assumes no conflict (validates at commit); Pessimistic locks data immediately before access", "Pessimistic assumes no conflict; Optimistic locks upfront", "Only pessimistic control is used in real databases"], answer: "Optimistic assumes no conflict (validates at commit); Pessimistic locks data immediately before access", explanation: "Optimistic is better for low-contention workloads; pessimistic for high-contention to prevent wasted work." },
      { q: "What is sharding in databases?", options: ["Database file compression", "Horizontally partitioning data across multiple database servers to achieve horizontal scalability", "Creating point-in-time backups", "Encrypting database columns"], answer: "Horizontally partitioning data across multiple database servers to achieve horizontal scalability", explanation: "Sharding distributes rows (e.g., by user ID range or hash) across servers, each holding a subset of data." },
      { q: "What is CAP Theorem?", options: ["A SQL optimization guide", "A theorem stating distributed databases can only simultaneously guarantee two of: Consistency, Availability, Partition Tolerance", "A database normalization methodology", "An indexing strategy for distributed data"], answer: "A theorem stating distributed databases can only simultaneously guarantee two of: Consistency, Availability, Partition Tolerance", explanation: "During a network partition, CP systems (e.g., HBase) return errors; AP systems (e.g., Cassandra) return stale data." },
      { q: "What is a materialized view?", options: ["A view rendered in the UI", "A precomputed, physically stored view that is periodically refreshed for fast read access", "A view that computes data fresh on each query", "A 3D database visualization"], answer: "A precomputed, physically stored view that is periodically refreshed for fast read access", explanation: "Materialized views trade freshness for speed. Useful for expensive aggregations in reporting/analytics." },
      { q: "What is MVCC (Multi-Version Concurrency Control)?", options: ["A multi-primary replication strategy", "A technique maintaining multiple data versions so readers never block writers", "A backup replication method", "A query planning algorithm"], answer: "A technique maintaining multiple data versions so readers never block writers", explanation: "MVCC (used in PostgreSQL, MySQL InnoDB) keeps old row versions so concurrent reads see a consistent snapshot without locking." },
      { q: "What are isolation levels in a DBMS?", options: ["Security access levels for users", "Levels defining what concurrent transactions can see of each other's uncommitted changes", "Replication lag thresholds", "Backup frequency settings"], answer: "Levels defining what concurrent transactions can see of each other's uncommitted changes", explanation: "Levels (Read Uncommitted, Read Committed, Repeatable Read, Serializable) trade consistency for concurrency. Higher = fewer anomalies, more locking." }
    ]
  },

  /* ==================== NETWORKS ==================== */
  "Networks": {
    "Easy": [
      { q: "What does LAN stand for?", options: ["Large Area Network", "Local Area Network", "Linked Access Network", "Logical Address Node"], answer: "Local Area Network", explanation: "LAN connects devices within a limited area (home, office, campus) typically via Ethernet or WiFi." },
      { q: "What is an IP address?", options: ["A website name", "A unique numerical label assigned to each device on a network", "A physical port number", "A server's name"], answer: "A unique numerical label assigned to each device on a network", explanation: "IPv4 addresses are 32-bit (e.g., 192.168.1.1); IPv6 addresses are 128-bit." },
      { q: "What does HTTP stand for?", options: ["HyperText Transfer Protocol", "Hyper Terminal Transfer Program", "High Transfer Text Protocol", "Host Transfer Technology Protocol"], answer: "HyperText Transfer Protocol", explanation: "HTTP is the application-layer protocol for transmitting web pages. HTTPS adds TLS encryption." },
      { q: "What does a Router do?", options: ["Connects cables physically", "Forwards data packets between different networks using routing tables", "Amplifies WiFi signal strength", "Stores network data"], answer: "Forwards data packets between different networks using routing tables", explanation: "Routers operate at Layer 3 (Network) and connect your home network to the internet." },
      { q: "What does DNS stand for?", options: ["Dynamic Naming Service", "Domain Name System", "Data Network Service", "Direct Node Server"], answer: "Domain Name System", explanation: "DNS translates human-readable domain names (google.com) to IP addresses (142.250.80.46)." },
      { q: "What is a MAC address?", options: ["An Apple device address", "A unique 48-bit hardware identifier assigned to each network interface card", "A virtual IP address", "A server's hostname"], answer: "A unique 48-bit hardware identifier assigned to each network interface card", explanation: "MAC addresses operate at Layer 2 (Data Link). They are written as 6 pairs of hex digits: AA:BB:CC:DD:EE:FF." },
      { q: "Which port does HTTP use by default?", options: ["21", "25", "80", "443"], answer: "80", explanation: "HTTP uses port 80; HTTPS uses 443; FTP uses 21; SMTP uses 25." },
      { q: "What is the difference between TCP and UDP?", options: ["They are identical", "TCP is reliable (connection-oriented, ordered delivery); UDP is faster but connectionless", "UDP is reliable; TCP is connectionless", "TCP is only for video; UDP for web"], answer: "TCP is reliable (connection-oriented, ordered delivery); UDP is faster but connectionless", explanation: "TCP: email, HTTP, FTP. UDP: video streaming, DNS, VoIP — where speed > reliability." },
      { q: "What is a Firewall?", options: ["A physical server barrier", "A security system monitoring and filtering network traffic based on predefined rules", "A type of router", "An antivirus program"], answer: "A security system monitoring and filtering network traffic based on predefined rules", explanation: "Firewalls can be hardware or software. They block unauthorized access while permitting legitimate traffic." },
      { q: "What is bandwidth?", options: ["Cable length", "The maximum data transfer rate of a network connection", "Number of connected devices", "Network security level"], answer: "The maximum data transfer rate of a network connection", explanation: "Bandwidth is measured in bps (bits per second). High bandwidth ≠ low latency; they are different metrics." }
    ],
    "Medium": [
      { q: "How many layers does the OSI model have?", options: ["4", "5", "7", "8"], answer: "7", explanation: "OSI: Physical, Data Link, Network, Transport, Session, Presentation, Application. TCP/IP model has 4 layers." },
      { q: "What is subnetting?", options: ["Building a physical sub-network", "Dividing an IP network into smaller logical sub-networks with subnet masks", "Connecting two separate networks", "Filtering broadcast traffic"], answer: "Dividing an IP network into smaller logical sub-networks with subnet masks", explanation: "Subnetting reduces broadcast domains, improves security, and allows efficient IP address allocation." },
      { q: "What is the purpose of DHCP?", options: ["Resolving domain names to IPs", "Automatically assigning IP addresses, subnet masks, and gateway info to devices", "Encrypting all network traffic", "Routing packets between networks"], answer: "Automatically assigning IP addresses, subnet masks, and gateway info to devices", explanation: "DHCP (Dynamic Host Configuration Protocol) eliminates manual IP configuration on each device." },
      { q: "What is ARP (Address Resolution Protocol) used for?", options: ["Translating domain names to IPs", "Mapping a known IP address to its physical MAC address on the local network", "Encrypting network packets", "Routing packets between ASes"], answer: "Mapping a known IP address to its physical MAC address on the local network", explanation: "When a device wants to send a packet on the LAN, it broadcasts 'Who has IP x.x.x.x?' ARP resolves the MAC." },
      { q: "What is NAT (Network Address Translation)?", options: ["Node Assignment Technique", "Translating private IP addresses to a shared public IP for internet access", "Network Access Testing", "Normalizing address tables"], answer: "Translating private IP addresses to a shared public IP for internet access", explanation: "NAT allows multiple devices with RFC 1918 private IPs to share one public IP, conserving IPv4 addresses." },
      { q: "What is the TCP three-way handshake?", options: ["A security authentication protocol", "The SYN → SYN-ACK → ACK process that establishes a TCP connection", "A routing protocol negotiation", "A DNS resolution sequence"], answer: "The SYN → SYN-ACK → ACK process that establishes a TCP connection", explanation: "Client sends SYN; server responds SYN-ACK (agreeing and sending its own SYN); client confirms with ACK." },
      { q: "What is the key difference between IPv4 and IPv6?", options: ["They are identical protocols", "IPv4 uses 32-bit addresses (~4.3B); IPv6 uses 128-bit addresses (3.4×10³⁸)", "IPv6 uses 32-bit; IPv4 uses 64-bit", "IPv4 supports encryption natively"], answer: "IPv4 uses 32-bit addresses (~4.3B); IPv6 uses 128-bit addresses (3.4×10³⁸)", explanation: "IPv4 address exhaustion drove IPv6 adoption. IPv6 also eliminates NAT, adds auto-configuration, and built-in IPsec." },
      { q: "What is a VLAN?", options: ["A very large area network", "A logically segmented broadcast domain within the same physical switch infrastructure", "A virtual router appliance", "A wireless network type"], answer: "A logically segmented broadcast domain within the same physical switch infrastructure", explanation: "VLANs improve security and performance by isolating traffic groups without separate physical hardware." },
      { q: "What is latency in networking?", options: ["Data transfer speed", "The time delay for a packet to travel from source to destination", "Packet size limit", "Number of simultaneous connections"], answer: "The time delay for a packet to travel from source to destination", explanation: "Latency (RTT) is measured in ms. High bandwidth doesn't guarantee low latency. Affected by distance, queuing, and processing." },
      { q: "What is a proxy server?", options: ["A backup server", "An intermediary server between clients and the internet for caching, filtering, or anonymity", "A primary DNS server", "A DHCP relay server"], answer: "An intermediary server between clients and the internet for caching, filtering, or anonymity", explanation: "Forward proxies serve clients; reverse proxies serve servers (load balancing, SSL termination). Used for privacy and content filtering." }
    ],
    "Hard": [
      { q: "What is BGP and why is it called 'the protocol that holds the internet together'?", options: ["A local network protocol", "Border Gateway Protocol — manages routing between Autonomous Systems across the entire internet", "A security encryption standard", "A wireless backhaul protocol"], answer: "Border Gateway Protocol — manages routing between Autonomous Systems across the entire internet", explanation: "BGP is the inter-AS routing protocol. ISPs use eBGP; within an AS, iBGP is used. BGP updates carry AS paths and reachability info." },
      { q: "What is the difference between symmetric and asymmetric encryption?", options: ["Speed only", "Symmetric: same key encrypts and decrypts; Asymmetric: public key encrypts, private key decrypts", "Asymmetric is weaker", "Symmetric uses public/private key pairs"], answer: "Symmetric: same key encrypts and decrypts; Asymmetric: public key encrypts, private key decrypts", explanation: "AES is symmetric (fast, for bulk data). RSA/ECC is asymmetric (slow, for key exchange and signatures). TLS uses both." },
      { q: "What is OSPF and what type of routing protocol is it?", options: ["Open Shortest Path First — a link-state interior gateway routing protocol", "Online Server Protection Framework", "A distance-vector routing protocol", "An exterior gateway protocol like BGP"], answer: "Open Shortest Path First — a link-state interior gateway routing protocol", explanation: "OSPF builds a complete topology map using LSAs, runs Dijkstra's SPF algorithm, and converges quickly within an AS." },
      { q: "What is a DDoS attack?", options: ["Data Duplication on Servers", "Distributed Denial of Service — flooding a target from many compromised hosts to make it unavailable", "Dynamic Data over Services attack", "Directed Data Output System"], answer: "Distributed Denial of Service — flooding a target from many compromised hosts to make it unavailable", explanation: "DDoS uses botnets to overwhelm bandwidth or server resources. Mitigated by scrubbing centers, rate limiting, and CDNs." },
      { q: "What does TLS provide?", options: ["Storage Layer Security for databases", "Encryption, authentication (via certificates), and integrity for network communications", "A server load balancing technique", "A DNS security extension only"], answer: "Encryption, authentication (via certificates), and integrity for network communications", explanation: "TLS (successor to SSL) is used in HTTPS, SMTP, and other protocols. It uses asymmetric key exchange then symmetric encryption." },
      { q: "What is a CDN and how does it improve performance?", options: ["A central data node", "A geographically distributed network of servers caching content close to end users", "A type of DNS service", "A backup network infrastructure"], answer: "A geographically distributed network of servers caching content close to end users", explanation: "CDNs (Cloudflare, Akamai) reduce latency by serving cached static content from servers near the user, reducing origin load." },
      { q: "What is MPLS (Multiprotocol Label Switching)?", options: ["A network security protocol", "A forwarding technique using short fixed-length labels instead of long IP addresses for fast routing", "A wireless standard", "A firewall architecture"], answer: "A forwarding technique using short fixed-length labels instead of long IP addresses for fast routing", explanation: "MPLS assigns labels at ingress, enabling routers to forward based on labels (not IP lookups), used in carrier networks." },
      { q: "What is Software-Defined Networking (SDN)?", options: ["Networks built purely in software simulation", "An architecture separating the control plane (routing decisions) from the data plane (packet forwarding)", "A wireless networking standard", "A server virtualization technique"], answer: "An architecture separating the control plane (routing decisions) from the data plane (packet forwarding)", explanation: "SDN enables centralized, programmable network management via controllers (e.g., OpenFlow), enabling dynamic policy enforcement." },
      { q: "What is congestion control in TCP?", options: ["Blocking certain users from the network", "Mechanisms like slow start, AIMD, and fast retransmit that prevent network overload", "Prioritizing premium traffic streams", "Encrypting congested traffic"], answer: "Mechanisms like slow start, AIMD, and fast retransmit that prevent network overload", explanation: "TCP starts with a small window (slow start), increases it additively, and halves on packet loss (AIMD — Additive Increase Multiplicative Decrease)." },
      { q: "What is the purpose of ICMP?", options: ["Transferring large files reliably", "Sending network error messages and diagnostic information (ping, traceroute)", "Establishing TCP connections", "Encrypting application layer data"], answer: "Sending network error messages and diagnostic information (ping, traceroute)", explanation: "ICMP (Internet Control Message Protocol) is used by ping (echo request/reply) and traceroute (TTL exceeded messages)." }
    ]
  }
};

/**
 * Retrieve the question array for a given subject and level.
 * Returns a copy so the original isn't mutated.
 */
function getQuestions(subject, level) {
  const bank = QUESTION_BANK[subject];
  return (bank && bank[level]) ? [...bank[level]] : [];
}

/**
 * Fisher-Yates shuffle — returns a new shuffled array.
 */
function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
